#! /bin/sh

PACKAGE=atril;

# normal translations
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot

# translations for user-quide
rm -f help/$PACKAGE.pot &&
make -C help $PACKAGE.pot
